[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = (YOUR_SERVER_PRIVATE_KEY_HERE)
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = (CLIENT_PUBLIC_KEY_HERE)
AllowedIPs = 10.0.0.2/32
